name: modules
description: Adds a module system to Dart resulting in a cleaner project structure.
repository: https://github.com/mcmah309/modules/tree/master/modules
version: 0.1.0

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.6.4

dev_dependencies:
  custom_lint:
